// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZulexPharma.Infrastructure.Data;

#nullable disable

namespace ZulexPharma.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331215543_AddProdutoFamilia")]
    partial class AddProdutoFamilia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Colaborador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Configuracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.DicionarioRelacionamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColunaFk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OnDelete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("restrict");

                    b.Property<string>("OnUpdate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("noAction");

                    b.Property<bool>("Revisado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TabelaAlvo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Tabela", "ColunaFk")
                        .IsUnique();

                    b.ToTable("DicionarioRelacionamentos");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.DicionarioRevisao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Coluna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstrucaoIA")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Revisado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Unico")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Tabela", "Coluna")
                        .IsUnique();

                    b.ToTable("DicionarioRevisoes");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.DicionarioTabela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("global");

                    b.Property<string>("InstrucaoIA")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Replica")
                        .HasColumnType("boolean");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Tabela")
                        .IsUnique();

                    b.ToTable("DicionarioTabelas");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Fabricante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Filial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Bloco")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CodigoTela")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeTela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermissoesAdicionais")
                        .HasColumnType("text");

                    b.Property<bool>("PodeAlterar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodeConsultar")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodeExcluir")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodeIncluir")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("GrupoUsuarioId");

                    b.ToTable("UsuariosGruposPermissao", (string)null);
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoPrincipal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoPercentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("ControlarLotesVencimento")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DescontoMaximo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMaximoComSenha")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMinimo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImprimirEtiqueta")
                        .HasColumnType("boolean");

                    b.Property<bool>("InformarPrescritorVenda")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarkupPadrao")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PermitirDescontoPrazo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirDescontosProgressivos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirPromocao")
                        .HasColumnType("boolean");

                    b.Property<string>("Priorizar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ProjecaoLucro")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("GruposPrincipais");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoProduto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoPercentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("ControlarLotesVencimento")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DescontoMaximo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMaximoComSenha")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMinimo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImprimirEtiqueta")
                        .HasColumnType("boolean");

                    b.Property<bool>("InformarPrescritorVenda")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarkupPadrao")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PermitirDescontoPrazo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirDescontosProgressivos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirPromocao")
                        .HasColumnType("boolean");

                    b.Property<string>("Priorizar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ProjecaoLucro")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("GruposProdutos");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("UsuariosGrupos", (string)null);
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.LogAcao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entidade")
                        .HasColumnType("text");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LiberacaoPorSenha")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistroId")
                        .HasColumnType("text");

                    b.Property<string>("Tela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioLiberouId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioLiberouId");

                    b.ToTable("LogsAcao");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.LogErro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAdicionais")
                        .HasColumnType("text");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Funcao")
                        .HasColumnType("text");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Tela")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioLogin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("LogsErro");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Ncm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CodigoNcm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExTipi")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("UnidadeTributavel")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("CodigoNcm")
                        .IsUnique();

                    b.ToTable("Ncms");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmFederal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AliquotaCofins")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("AliquotaIi")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("AliquotaIpi")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("AliquotaPis")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CstCofins")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CstIpi")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CstPis")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("NcmId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("NcmId");

                    b.ToTable("NcmFederais");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmIcmsUf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AliquotaFcp")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("AliquotaIcms")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cbenef")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Csosn")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("CstIcms")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("NcmId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ReducaoBaseCalculo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("NcmId", "Uf")
                        .IsUnique();

                    b.ToTable("NcmIcmsUfs");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmStUf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AliquotaIcmsSt")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cest")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Mva")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MvaAjustado")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long>("NcmId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ReducaoBaseCalculoSt")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("UfDestino")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("UfOrigem")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("NcmId", "UfOrigem", "UfDestino")
                        .IsUnique();

                    b.ToTable("NcmStUfs");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.PessoaContato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoasContato");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.PessoaEndereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoasEndereco");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.ProdutoFamilia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("ProdutoFamilias");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Secao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoPercentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("ControlarLotesVencimento")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DescontoMaximo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMaximoComSenha")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMinimo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImprimirEtiqueta")
                        .HasColumnType("boolean");

                    b.Property<bool>("InformarPrescritorVenda")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarkupPadrao")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PermitirDescontoPrazo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirDescontosProgressivos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirPromocao")
                        .HasColumnType("boolean");

                    b.Property<string>("Priorizar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ProjecaoLucro")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("Secoes");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.SequenciaLocal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Ultimo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Tabela")
                        .IsUnique();

                    b.ToTable("SequenciasLocais");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.SubGrupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoPercentual")
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("ControlarLotesVencimento")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DescontoMaximo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMaximoComSenha")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescontoMinimo")
                        .HasColumnType("numeric(5,2)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ImprimirEtiqueta")
                        .HasColumnType("boolean");

                    b.Property<bool>("InformarPrescritorVenda")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarkupPadrao")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PermitirDescontoPrazo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirDescontosProgressivos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirPromocao")
                        .HasColumnType("boolean");

                    b.Property<string>("Priorizar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ProjecaoLucro")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("SubGrupos");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Substancia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClasseTerapeutica")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<bool>("ControleEspecialSngpc")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dcb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.ToTable("Substancias");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.SyncFila", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosJson")
                        .HasColumnType("text");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Erro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("RegistroCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("RegistroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Enviado");

                    b.HasIndex("FilialOrigemId");

                    b.ToTable("SyncFila");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<long?>("ColaboradorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("FilialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("InatividadeMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdministrador")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SessaoMaximaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("ColaboradorId")
                        .IsUnique();

                    b.HasIndex("FilialId");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.UsuarioFilialGrupo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FilialId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FilialOrigemId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrupoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("FilialId");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("UsuarioId", "FilialId", "GrupoUsuarioId")
                        .IsUnique();

                    b.ToTable("UsuarioFilialGrupos");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Colaborador")
                        .HasForeignKey("ZulexPharma.Domain.Entities.Colaborador", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Pessoa", "Pessoa")
                        .WithOne("Fornecedor")
                        .HasForeignKey("ZulexPharma.Domain.Entities.Fornecedor", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoPermissao", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.GrupoUsuario", "GrupoUsuario")
                        .WithMany("Permissoes")
                        .HasForeignKey("GrupoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoUsuario");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.LogAcao", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsAcoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZulexPharma.Domain.Entities.Usuario", "UsuarioLiberou")
                        .WithMany()
                        .HasForeignKey("UsuarioLiberouId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioLiberou");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmFederal", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Ncm", "Ncm")
                        .WithMany("Federais")
                        .HasForeignKey("NcmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ncm");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmIcmsUf", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Ncm", "Ncm")
                        .WithMany("IcmsUfs")
                        .HasForeignKey("NcmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ncm");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.NcmStUf", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Ncm", "Ncm")
                        .WithMany("StUfs")
                        .HasForeignKey("NcmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ncm");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.PessoaContato", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.PessoaEndereco", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Colaborador", "Colaborador")
                        .WithOne("Usuario")
                        .HasForeignKey("ZulexPharma.Domain.Entities.Usuario", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ZulexPharma.Domain.Entities.Filial", "Filial")
                        .WithMany("Usuarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZulexPharma.Domain.Entities.GrupoUsuario", "GrupoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Filial");

                    b.Navigation("GrupoUsuario");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.UsuarioFilialGrupo", b =>
                {
                    b.HasOne("ZulexPharma.Domain.Entities.Filial", "Filial")
                        .WithMany("UsuarioFilialGrupos")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZulexPharma.Domain.Entities.GrupoUsuario", "GrupoUsuario")
                        .WithMany("UsuarioFilialGrupos")
                        .HasForeignKey("GrupoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZulexPharma.Domain.Entities.Usuario", "Usuario")
                        .WithMany("FilialGrupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");

                    b.Navigation("GrupoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Colaborador", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Filial", b =>
                {
                    b.Navigation("UsuarioFilialGrupos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.GrupoUsuario", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("UsuarioFilialGrupos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Ncm", b =>
                {
                    b.Navigation("Federais");

                    b.Navigation("IcmsUfs");

                    b.Navigation("StUfs");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Colaborador");

                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ZulexPharma.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("FilialGrupos");

                    b.Navigation("LogsAcoes");
                });
#pragma warning restore 612, 618
        }
    }
}
