USE [INOVAFARMA_FARMACIAMAXIFARMA_FILIAL3]
GO

/****** Object:  Table [dbo].[Fiscal_CSTCSOSN_ICMS]    Script Date: 26/04/2026 05:33:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Fiscal_CSTCSOSN_ICMS](
	[CodigoCSTCSOSN] [varchar](3) NOT NULL,
	[Descricao] [varchar](300) NOT NULL,
	[Tipo] [tinyint] NOT NULL,
	[FinalidadeEntrada] [bit] NOT NULL,
	[FinalidadeSaida] [bit] NOT NULL,
 CONSTRAINT [PK_Fiscal_CSTCSOSN_ICMS] PRIMARY KEY CLUSTERED 
(
	[CodigoCSTCSOSN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

