USE [INOVAFARMA_FARMACIAMAXIFARMA_FILIAL3]
GO

/****** Object:  Table [dbo].[Produto_NCM_Decreto]    Script Date: 25/04/2026 18:54:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Produto_NCM_Decreto](
	[CodigoDecreto] [smallint] NOT NULL,
	[Historico] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Produto_NCM_Decreto] PRIMARY KEY CLUSTERED 
(
	[CodigoDecreto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

