export interface Banco {
  codigo: string;
  nome: string;
}

export const BANCOS_BRASIL: Banco[] = [
  { codigo: '001', nome: 'Banco do Brasil' },
  { codigo: '003', nome: 'Banco da Amazônia' },
  { codigo: '004', nome: 'Banco do Nordeste' },
  { codigo: '010', nome: 'Credicoamo' },
  { codigo: '012', nome: 'Banco Inbursa' },
  { codigo: '021', nome: 'Banestes' },
  { codigo: '025', nome: 'Banco Alfa' },
  { codigo: '029', nome: 'Banco Itaú Consignado' },
  { codigo: '033', nome: 'Banco Santander' },
  { codigo: '036', nome: 'Banco Bradesco BBI' },
  { codigo: '037', nome: 'Banco do Estado do Pará' },
  { codigo: '041', nome: 'Banrisul' },
  { codigo: '047', nome: 'Banco do Estado de Sergipe' },
  { codigo: '062', nome: 'Hipercard' },
  { codigo: '063', nome: 'Banco Bradescard' },
  { codigo: '065', nome: 'Banco AndBank' },
  { codigo: '066', nome: 'Banco Morgan Stanley' },
  { codigo: '069', nome: 'Banco Crefisa' },
  { codigo: '070', nome: 'BRB - Banco de Brasília' },
  { codigo: '074', nome: 'Banco Safra' },
  { codigo: '077', nome: 'Banco Inter' },
  { codigo: '079', nome: 'Banco Original do Agronegócio' },
  { codigo: '082', nome: 'Banco Topázio' },
  { codigo: '084', nome: 'Uniprime Norte do Paraná' },
  { codigo: '085', nome: 'Cooperativa Central Ailos' },
  { codigo: '089', nome: 'Cooperativa de Crédito Credisan' },
  { codigo: '091', nome: 'Unicred Central RS' },
  { codigo: '093', nome: 'PóloCred' },
  { codigo: '094', nome: 'Banco Finaxis' },
  { codigo: '096', nome: 'Banco B3' },
  { codigo: '097', nome: 'Cooperativa Central de Crédito Noroeste Brasileiro' },
  { codigo: '099', nome: 'Uniprime Central' },
  { codigo: '104', nome: 'Caixa Econômica Federal' },
  { codigo: '107', nome: 'Banco Bocom BBM' },
  { codigo: '114', nome: 'Central das Cooperativas de Economia e Crédito do Estado do Espírito Santo' },
  { codigo: '119', nome: 'Banco Western Union' },
  { codigo: '120', nome: 'Banco Rodobens' },
  { codigo: '121', nome: 'Banco Agibank' },
  { codigo: '125', nome: 'Banco Genial' },
  { codigo: '128', nome: 'MS Bank' },
  { codigo: '133', nome: 'Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Solidária' },
  { codigo: '136', nome: 'Unicred do Brasil' },
  { codigo: '144', nome: 'Bexs Banco de Câmbio' },
  { codigo: '169', nome: 'Banco Olé Bonsucesso Consignado' },
  { codigo: '174', nome: 'Pefisa' },
  { codigo: '184', nome: 'Banco Itaú BBA' },
  { codigo: '197', nome: 'Stone Pagamentos' },
  { codigo: '208', nome: 'Banco BTG Pactual' },
  { codigo: '212', nome: 'Banco Original' },
  { codigo: '213', nome: 'Banco Arbi' },
  { codigo: '217', nome: 'Banco John Deere' },
  { codigo: '218', nome: 'Banco BS2' },
  { codigo: '222', nome: 'Banco Credit Agricole Brasil' },
  { codigo: '224', nome: 'Banco Fibra' },
  { codigo: '233', nome: 'Banco Cifra' },
  { codigo: '237', nome: 'Banco Bradesco' },
  { codigo: '241', nome: 'Banco Clássico' },
  { codigo: '243', nome: 'Banco Máxima' },
  { codigo: '246', nome: 'Banco ABC Brasil' },
  { codigo: '249', nome: 'Banco Investcred Unibanco' },
  { codigo: '254', nome: 'Paraná Banco' },
  { codigo: '260', nome: 'Nu Pagamentos (Nubank)' },
  { codigo: '265', nome: 'Banco Fator' },
  { codigo: '269', nome: 'HSBC Brasil' },
  { codigo: '270', nome: 'Sagitur' },
  { codigo: '276', nome: 'Banco Senff' },
  { codigo: '280', nome: 'Avista' },
  { codigo: '290', nome: 'PagSeguro Internet' },
  { codigo: '299', nome: 'Banco Sorocred' },
  { codigo: '301', nome: 'BPP Instituição de Pagamento' },
  { codigo: '318', nome: 'Banco BMG' },
  { codigo: '320', nome: 'Banco CCB Brasil' },
  { codigo: '323', nome: 'Mercado Pago' },
  { codigo: '329', nome: 'QI Sociedade de Crédito Direto' },
  { codigo: '335', nome: 'Banco Digio' },
  { codigo: '336', nome: 'Banco C6' },
  { codigo: '340', nome: 'Super Pagamentos (Superdigital)' },
  { codigo: '341', nome: 'Banco Itaú Unibanco' },
  { codigo: '364', nome: 'Gerencianet (Efí)' },
  { codigo: '376', nome: 'Banco J.P. Morgan' },
  { codigo: '380', nome: 'PicPay' },
  { codigo: '389', nome: 'Banco Mercantil do Brasil' },
  { codigo: '394', nome: 'Banco Bradesco Financiamentos' },
  { codigo: '399', nome: 'Kirton Bank' },
  { codigo: '403', nome: 'Banco Cora' },
  { codigo: '412', nome: 'Banco Capital' },
  { codigo: '422', nome: 'Banco Safra' },
  { codigo: '456', nome: 'Banco MUFG Brasil' },
  { codigo: '473', nome: 'Banco Caixa Geral' },
  { codigo: '477', nome: 'Citibank' },
  { codigo: '487', nome: 'Deutsche Bank' },
  { codigo: '604', nome: 'Banco Industrial do Brasil' },
  { codigo: '610', nome: 'Banco VR' },
  { codigo: '611', nome: 'Banco Paulista' },
  { codigo: '612', nome: 'Banco Guanabara' },
  { codigo: '613', nome: 'Omni Banco' },
  { codigo: '623', nome: 'Banco Pan' },
  { codigo: '626', nome: 'Banco C6 Consignado' },
  { codigo: '630', nome: 'Banco Smartbank' },
  { codigo: '633', nome: 'Banco Rendimento' },
  { codigo: '634', nome: 'Banco Triângulo' },
  { codigo: '637', nome: 'Banco Sofisa' },
  { codigo: '643', nome: 'Banco Pine' },
  { codigo: '654', nome: 'Banco Digimais' },
  { codigo: '655', nome: 'Banco Votorantim' },
  { codigo: '707', nome: 'Banco Daycoval' },
  { codigo: '712', nome: 'Banco Ourinvest' },
  { codigo: '739', nome: 'Banco Cetelem' },
  { codigo: '741', nome: 'Banco Ribeirão Preto' },
  { codigo: '743', nome: 'Banco Semear' },
  { codigo: '745', nome: 'Banco Citibank' },
  { codigo: '746', nome: 'Banco Modal' },
  { codigo: '748', nome: 'Sicredi' },
  { codigo: '752', nome: 'Banco BNP Paribas Brasil' },
  { codigo: '755', nome: 'Bank of America Merrill Lynch' },
  { codigo: '756', nome: 'Sicoob' },
  { codigo: '757', nome: 'Banco KEB Hana do Brasil' },
];
